#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <program command> <file_name>"
    exit 1
fi

cmd="$1"
file_name="$2".csv

test -z "$file_name" && rm -f "$file_name"
column_names=$(nvidia-smi -q | grep "GPU UUID" | tr -s " " "," | cut -d , -f 5 | tr -s "\n" ",")
printf "%s\n" "${column_names%,}"  >> "$file_name"

function sampler
{
    while true; do
        sample=$(nvidia-smi -q | grep "Power Draw" | tr -s " " "," | cut  -d , -f 5 | tr -s "\n" ",")
        printf "%s\n" "${sample%,}"  >> "$file_name"
    done
}

# start sampler
sampler &
sleep 10
sampler_pid=$!
$cmd
sleep 10
kill $sampler_pid
